# Generated by Django 6.0.2 on 2026-03-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department_head', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeerequestitem',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
    ]
