# Generated by Django 6.0.2 on 2026-03-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department_head', '0003_alter_employeerequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeerequest',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Approved by Dean', 'Approved by Dean'), ('Rejected by Dean', 'Rejected by Dean'), ('Forwarded to VP', 'Forwarded to VP'), ('Approved by VP', 'Approved by VP'), ('Rejected by VP', 'Rejected by VP'), ('Forwarded to HR', 'Forwarded to HR'), ('Vacancy Announced', 'Vacancy Announced'), ('Screening', 'Screening'), ('Interview', 'Interview'), ('Hiring Completed', 'Hiring Completed')], default='Submitted', max_length=50),
        ),
        migrations.AlterField(
            model_name='employeerequestitem',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('A', 'Any')], default='M', max_length=1),
        ),
    ]
