# Generated by Django 6.0.2 on 2026-04-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department_head', '0004_alter_employeerequest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerequest',
            name='ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeerequest',
            name='request_narrative',
            field=models.TextField(blank=True),
        ),
    ]
