# Generated by Django 6.0.2 on 2026-04-18 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department_head', '0005_employeerequest_ai_generated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeerequest',
            name='description',
        ),
    ]
