# Generated by Django 6.0.2 on 2026-04-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department_head', '0006_remove_employeerequest_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeerequestitem',
            name='area_of_specialization',
        ),
        migrations.AddField(
            model_name='employeerequestitem',
            name='department',
            field=models.CharField(default='Not Specified', help_text='Department where the applicant completed their studies', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeerequestitem',
            name='academic_qualification',
            field=models.CharField(choices=[('BSc', 'Bachelor Degree'), ('MSc', 'Master’s Degree'), ('PhD', 'PhD')], max_length=10),
        ),
        migrations.AlterField(
            model_name='employeerequestitem',
            name='academic_rank',
            field=models.CharField(choices=[('LECTURER', 'Lecturer'), ('ASST_PROF', 'Assistant Professor'), ('ASSOC_PROF', 'Associate Professor'), ('PROFESSOR', 'Professor')], max_length=20),
        ),
    ]
