# Generated by Django 6.0.2 on 2026-04-18 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department_head', '0007_remove_employeerequestitem_area_of_specialization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeerequest',
            name='closing_note',
        ),
    ]
