# Generated by Django 6.0.2 on 2026-04-19 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department_head', '0008_remove_employeerequest_closing_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeerequestitem',
            old_name='department',
            new_name='study_department',
        ),
        migrations.RemoveField(
            model_name='employeerequestitem',
            name='sex',
        ),
        migrations.AlterField(
            model_name='employeerequestitem',
            name='cgpa_requirement',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='employeerequestitem',
            name='experience_years',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employeerequestitem',
            name='number_of_employees',
            field=models.IntegerField(default=1),
        ),
    ]
