# Generated by Django 6.0.2 on 2026-04-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_hr_notes_application_ranking_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('eligible', 'Eligible'), ('shortlisted', 'Shortlisted'), ('exam', 'Exam'), ('rejected', 'Rejected'), ('interview', 'Interview'), ('final_selection', 'Final Selection')], default='submitted', max_length=20),
        ),
    ]
