# Generated by Django 6.0.2 on 2026-04-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ai_summary',
            field=models.TextField(blank=True),
        ),
    ]
