# Generated by Django 6.0.2 on 2026-03-24 08:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_vp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpaction',
            name='action',
            field=models.CharField(choices=[('Approved by VP', 'Approved by VP'), ('Rejected by VP', 'Rejected by VP'), ('Forwarded to HR', 'Forwarded to HR')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vpaction',
            name='performed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
