# Generated by Django 6.0.2 on 2026-03-05 10:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department_head', '0002_alter_employeerequestitem_sex'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeanAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('forwarded', 'Forwarded to VP')], max_length=16)),
                ('reason', models.TextField(blank=True)),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dean_actions', to='department_head.employeerequest')),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='DeanProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('bio', models.TextField(blank=True)),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deans', to='organization.college')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deanprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
