# Generated by Django 6.0.2 on 2026-03-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_dean', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deanaction',
            name='action',
            field=models.CharField(choices=[('Approved by Dean', 'Approved by Dean'), ('Rejected by Dean', 'Rejected by Dean'), ('Forwarded to VP', 'Forwarded to VP')], max_length=50),
        ),
    ]
