# Generated by Django 6.0.2 on 2026-03-24 08:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department_head', '0004_alter_employeerequest_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HRAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('vacancy', 'Vacancy Announced'), ('screening', 'Screening'), ('interview', 'Interview'), ('hired', 'Hiring Completed')], max_length=50)),
                ('note', models.TextField(blank=True)),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_actions', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_actions', to='department_head.employeerequest')),
            ],
            options={
                'verbose_name': 'HR Action',
                'verbose_name_plural': 'HR Actions',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='HRProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('office_location', models.CharField(blank=True, max_length=128)),
                ('bio', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hrprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
