# Generated by Django 6.0.2 on 2026-04-12 08:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0003_alter_educationqualification_options_and_more'),
        ('department_head', '0004_alter_employeerequest_status_and_more'),
        ('hr_officer', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_date', models.DateField(default=django.utils.timezone.now)),
                ('deadline', models.DateField()),
                ('description', models.TextField()),
                ('application_instructions', models.TextField()),
                ('requirements', models.TextField(blank=True)),
                ('salary_info', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy', to='department_head.employeerequest')),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies_posted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-announcement_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VacancyPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_rank', models.CharField(max_length=128)),
                ('field_of_education', models.CharField(max_length=255)),
                ('minimum_cgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('positions', models.PositiveIntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_positions', to='organization.department')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='hr_officer.vacancy')),
            ],
            options={
                'verbose_name': 'Vacancy Position',
                'verbose_name_plural': 'Vacancy Positions',
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('interviewed', 'Interviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='submitted', max_length=32)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
                ('applicant_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_applications', to='applicant.applicantprofile')),
                ('vacancy_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='hr_officer.vacancyposition')),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('applicant', 'vacancy_position')},
            },
        ),
    ]
