# Generated by Django 6.0.2 on 2026-04-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_officer', '0002_vacancy_vacancyposition_jobapplication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hraction',
            options={'ordering': ['-performed_at']},
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='requirements',
            new_name='required_skills',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='description',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='announcement_text',
            field=models.TextField(default='', help_text='Final vacancy announcement text (AI generated and edited by HR)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='experience_requirement',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='vacancy_type',
            field=models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], default='internal', max_length=20),
            preserve_default=False,
        ),
    ]
