# Generated by Django 6.0.2 on 2026-04-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_officer', '0003_alter_hraction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='announcement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
