# Generated by Django 6.0.2 on 2026-04-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_officer', '0004_alter_vacancy_announcement_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancyposition',
            options={},
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='announcement_text',
            field=models.TextField(blank=True, help_text='AI generated + HR edited final vacancy text'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='application_instructions',
            field=models.TextField(blank=True),
        ),
    ]
