# Generated by Django 6.0.2 on 2026-04-29 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr_officer', '0005_alter_vacancyposition_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='closed_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_vacancies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
