# Generated by Django 6.0.2 on 2026-05-01 21:45

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_officer', '0006_add_vacancy_closure_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='shortlist_finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='announcement_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='deadline',
            field=models.DateField(default=datetime.date(2026, 5, 1)),
            preserve_default=False,
        ),
    ]
