# Generated by Django 6.0.2 on 2026-04-24 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=512)),
                ('is_read', models.BooleanField(default=False)),
                ('notification_type', models.CharField(choices=[('application_submitted', 'Application Submitted'), ('eligible', 'Eligible'), ('rejected', 'Rejected'), ('shortlisted', 'Shortlisted'), ('vacancy_match', 'Vacancy Match')], default='application_submitted', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
