# Generated by Django 6.0.2 on 2026-05-01 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('application_submitted', 'Application Submitted'), ('eligible', 'Eligible'), ('rejected', 'Rejected'), ('shortlisted', 'Shortlisted'), ('vacancy_match', 'Vacancy Match'), ('exam_scheduled', 'Exam Scheduled'), ('exam_started', 'Exam Started'), ('exam_result', 'Exam Result'), ('exam_completed', 'Exam Completed'), ('shortlist_finalized', 'Shortlist Finalized')], default='application_submitted', max_length=50),
        ),
    ]
