# Generated by Django 6.0.2 on 2026-04-09 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mobile_number', models.CharField(blank=True, max_length=20)),
                ('father_name', models.CharField(blank=True, max_length=64)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('ethnic_group', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('zone', models.CharField(blank=True, max_length=100)),
                ('wereda', models.CharField(blank=True, max_length=100)),
                ('kebele', models.CharField(blank=True, max_length=100)),
                ('house_number', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('phone_home', models.CharField(blank=True, max_length=20)),
                ('phone_work', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Applicant Profile',
                'verbose_name_plural': 'Applicant Profiles',
            },
        ),
        migrations.CreateModel(
            name='EducationQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_name', models.CharField(max_length=255)),
                ('qualification_category', models.CharField(max_length=255)),
                ('qualification_type', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('qualification_title', models.CharField(max_length=255)),
                ('grade', models.DecimalField(decimal_places=2, max_digits=4)),
                ('graduation_month', models.CharField(max_length=20)),
                ('graduation_year', models.PositiveIntegerField()),
                ('diploma_certificate', models.FileField(blank=True, null=True, upload_to='applicant/qualifications/')),
                ('transcript', models.FileField(blank=True, null=True, upload_to='applicant/qualifications/')),
                ('cost_sharing_document', models.FileField(blank=True, null=True, upload_to='applicant/qualifications/')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='applicant.applicantprofile')),
            ],
            options={
                'verbose_name': 'Education Qualification',
                'verbose_name_plural': 'Education Qualifications',
                'ordering': ['-graduation_year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmploymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_category', models.CharField(max_length=255)),
                ('employer', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('experience_letter', models.FileField(blank=True, null=True, upload_to='applicant/experiences/')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employments', to='applicant.applicantprofile')),
            ],
            options={
                'verbose_name': 'Employment History',
                'verbose_name_plural': 'Employment Histories',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ApplicantDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('resume', 'Resume (CV)'), ('grade8', 'Grade 8 Certificate')], max_length=20)),
                ('file', models.FileField(upload_to='applicant/documents/')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applicant.applicantprofile')),
            ],
            options={
                'verbose_name': 'Applicant Document',
                'verbose_name_plural': 'Applicant Documents',
                'unique_together': {('applicant', 'document_type')},
            },
        ),
    ]
