# Generated by Django 6.0.2 on 2026-04-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantprofile',
            name='ethnic_group',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='phone_home',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='phone_work',
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=20),
        ),
    ]
