# Generated by Django 6.0.2 on 2026-04-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0002_remove_applicantprofile_ethnic_group_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationqualification',
            options={'ordering': ['-end_date']},
        ),
        migrations.RemoveField(
            model_name='educationqualification',
            name='graduation_month',
        ),
        migrations.RemoveField(
            model_name='educationqualification',
            name='graduation_year',
        ),
        migrations.RemoveField(
            model_name='educationqualification',
            name='qualification_title',
        ),
        migrations.AddField(
            model_name='educationqualification',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationqualification',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='educationqualification',
            name='qualification_category',
            field=models.CharField(choices=[('bachelor', 'Bachelor Degree'), ('post_graduate', 'Post Graduate Education'), ('doctorate', 'Doctorate')], max_length=50),
        ),
    ]
