# Generated by Django 6.0.2 on 2026-05-02 02:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_application_ai_summary'),
        ('examinations', '0003_question_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='examsession',
            constraint=models.UniqueConstraint(fields=('exam', 'application'), name='unique_exam_application_session'),
        ),
    ]
