# Generated by Django 6.0.2 on 2026-05-02 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0004_examsession_unique_exam_application_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='Scheduled start time for the exam', null=True),
        ),
        migrations.AddField(
            model_name='examsession',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('ACTIVE', 'Active'), ('FINISHED', 'Finished')], default='NOT_STARTED', max_length=20),
        ),
    ]
